name: deployement

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug SSH
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}} | ${{ secrets.GITHUB_TOKEN }}"
      - name: setup ssh keys and permissions
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}
        
      - name: scan key
        run: ssh-keyscan -H songon.space >> ~/.ssh/known_hosts
      - name: pull and restart compose
        run: |
          ssh -i ~/.ssh/id_rsa root@songon.space "cd /home/ubuntu/blankpage && git pull && docker compose restart"
